spring.application.name=Internship_Payment_Service

spring.mongodb.uri=mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=admin


app.liquibase.change-log=db/changelog/changelog-master.yaml

spring.kafka.bootstrap-servers=${KAFKA_URL}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

jwt.secret=${JWT_SECRET}